version: '3.4'

services:
  wqrhttps:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB: test
      COLLECTION: wqr
      LAKE_NAME_COLLECTION: lake_names
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "build/index.js"]

  mongo:
      container_name: mongodb-test
      image: mongodb/mongodb-community-server
      environment:
        NODE_ENV: development
      ports:
        - 27017:27017