version: '3.4'

services:
  wqrhttps:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB: wqr
      COLLECTION: timeseries
      LAKE_NAME_COLLECTION: lake_names
    ports:
      - 3000:3000
    restart: always
    command: ["node", "build/index.js"]
  mongo:
    container_name: wqr_database
    image: mongodb/mongodb-community-server
    environment:
      NODE_ENV: production
    restart: always